# Generated by Django 3.2 on 2021-05-25 06:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('preview', models.TextField()),
                ('blog', ckeditor.fields.RichTextField()),
                ('views', models.IntegerField(blank=True, default=2000, null=True)),
                ('comments', models.IntegerField(blank=True, default=20, null=True)),
                ('author', models.CharField(max_length=50)),
                ('reading_time', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
