# Generated by Django 3.2 on 2021-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_link',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2018/04/10/13/35/africa-3307337__340.jpg', max_length=2000),
            preserve_default=False,
        ),
    ]
